FROM docker.io/library/openjdk:17-jdk-alpine
MAINTAINER hualongfeiyyy@163.com

RUN mkdir /app
ADD ./spring-boot-helloworld-0.9.6-SNAPSHOT.jar /app

WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "spring-boot-helloworld-0.9.6-SNAPSHOT.jar"]
