# Use the httpd-parent image as base
# Containerfile to build child image
FROM quay.io/redhattraining/httpd-parent:latest

# Then run ONBUILD instruction based parent image after FROM instruction.

# If child image will be deployed on OpenShift, LABEL instruction will
# define metadata displayed during running 'oc new-app' command.
LABEL io.k8s.description="A basic Apache HTTP Server child image, use ONBUILD" \
			io.k8s.display-name="Apache HTTP Server" \
			io.openshift.expose-services="8080:http" \
			io.openshift.tags="apache, httpd"

# ESSENTIAL for OpenShift:
# Change 80 port to 8080 port for random userid on OpenShift.
# Because progress of random userid in pod of OpenShift can't be binded on port
# less then 1024.
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
		sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

# ESSENTIAL for OpenShift:
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
		chmod -R g=u /var/log/httpd /var/run/httpd

# ESSENTIAL for OpenShift:
# use regular user to run progress which will overwrite USER instruction in parent image.
USER 1001

# EXPOSE instruction will overwrite in parent image.
EXPOSE 8080

