FROM docker.io/library/rockylinux:9.3
MAINTAINER hualongfeiyyy@163.com

# install nodejs 18
RUN curl -sL https://rpm.nodesource.com/setup_18.x | bash - && \
    dnf install -y nodejs && \
    npm install -g pnpm@10.11.0
